/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package DriftCorrection;

import javax.swing.SwingUtilities;

import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.StringTokenizer;
import java.util.logging.*;

import DriftCorrection.gui.MainFrame;
import DriftCorrection.process.Controller;
import static DriftCorrection.utils.Constants.CBIS_ROOT_DIR;
import static DriftCorrection.utils.Constants.VERSION;
import static DriftCorrection.utils.Constants.VERSION_CHECK_FILE;

public class App {
	
	private static final Logger logger = Logger.getLogger(App.class.getName());
	
	public App() {
		// check environment
		String currDir = System.getProperty("user.dir");
		
		FileHandler fh = null;  
		
		try {  

			// This block configure the logger with handler and formatter  
			fh = new FileHandler(currDir + "/DriftCorrection.log");  
			logger.addHandler(fh);
			SimpleFormatter formatter = new SimpleFormatter();  
			fh.setFormatter(formatter);  

			// the following statement is used to log any messages  
			logger.info("---------------New session----------------");  

		} catch (SecurityException e) {  
			e.printStackTrace();  
		} catch (IOException e) {  
			e.printStackTrace();  
		}  
		
		if (currDir.substring(0, 14).equals(CBIS_ROOT_DIR)) {
			String latestVersion = readLatestVersion();
			if (isOutdated(VERSION, latestVersion)) {
				logger.severe("current version is too old, please get newer version from scratch/utkur/hongwei/DriftCorrection/ for "
						+ "important updates.");
				System.exit(0);
			}
		}
		
		logger.setLevel(Level.FINE);
		logger.info("starting the program...");
		logger.info("running at: " + currDir);
		logger.info("number of processors: " + Runtime.getRuntime().availableProcessors());
		
		Controller controller = new Controller();
		controller.setFileHandler(fh);
		new MainFrame(controller, fh);
	}
	
	private String readLatestVersion() {
		String line = VERSION;
		try(BufferedReader br = new BufferedReader(new FileReader(VERSION_CHECK_FILE))) {
		    line = br.readLine();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		return line;
	}
	
    private boolean isOutdated(String current, String latest) {
    	StringTokenizer currentTokenizer = new StringTokenizer(current);
    	StringTokenizer latestTokenizer = new StringTokenizer(latest);
    	String curr = currentTokenizer.nextToken();
    	String late = latestTokenizer.nextToken();
    	if (Integer.parseInt(curr) < Integer.parseInt(late)) {
    		return true;
    	}
    	curr = currentTokenizer.nextToken();
    	late = latestTokenizer.nextToken();
    	if (Integer.parseInt(curr) < Integer.parseInt(late)) {
    		return true;
    	}
    	return false;
    }
	
    public static void main(String[] args) {
		
		SwingUtilities.invokeLater(new Runnable() {
			@Override
			public void run() {
				new App();
			}
		});	
		
		
	}
}
